#!/bin/sh

#SBATCH --job-name={{.job_id}}
#SBATCH --time={{.time}}
#SBATCH --mail-user={{.email}}
#SBATCH --mail-type={{.mailtype}}
#SBATCH --mem={{.memory}}
#SBATCH --cpus-per-task={{.cpus}}
#SBATCH -e "{{.error_path}}"
#SBATCH -o "{{.output_path}}"

R CMD BATCH --no-save --no-restore {{.path_to_script}} {{.output_path}}.Rout
